# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "keyrack"
  s.version = "0.3.0.pre"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jeremy Stephens"]
  s.date = "2012-01-11"
  s.description = "Simple password manager with local/remote database storage and RSA encryption."
  s.email = "viking@pillageandplunder.net"
  s.executables = ["keyrack"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc",
    "TODO"
  ]
  s.files = [
    ".document",
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "TODO",
    "VERSION",
    "bin/keyrack",
    "features/console.feature",
    "features/step_definitions/keyrack_steps.rb",
    "features/support/env.rb",
    "keyrack.gemspec",
    "lib/keyrack.rb",
    "lib/keyrack/database.rb",
    "lib/keyrack/runner.rb",
    "lib/keyrack/store.rb",
    "lib/keyrack/store/filesystem.rb",
    "lib/keyrack/store/ssh.rb",
    "lib/keyrack/ui.rb",
    "lib/keyrack/ui/console.rb",
    "lib/keyrack/utils.rb",
    "test/fixtures/aes",
    "test/fixtures/config.yml",
    "test/fixtures/foo.txt",
    "test/fixtures/id_rsa",
    "test/helper.rb",
    "test/keyrack/store/test_filesystem.rb",
    "test/keyrack/store/test_ssh.rb",
    "test/keyrack/test_database.rb",
    "test/keyrack/test_runner.rb",
    "test/keyrack/test_store.rb",
    "test/keyrack/test_utils.rb",
    "test/keyrack/ui/test_console.rb"
  ]
  s.homepage = "http://github.com/viking/keyrack"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.11"
  s.summary = "Simple password manager"
  s.test_files = [
    "test/helper.rb",
    "test/keyrack/store/test_filesystem.rb",
    "test/keyrack/store/test_ssh.rb",
    "test/keyrack/test_database.rb",
    "test/keyrack/test_runner.rb",
    "test/keyrack/test_store.rb",
    "test/keyrack/test_utils.rb",
    "test/keyrack/ui/test_console.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<net-scp>, [">= 0"])
      s.add_runtime_dependency(%q<highline>, [">= 0"])
      s.add_runtime_dependency(%q<copier>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<mocha>, [">= 0"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_development_dependency(%q<test-unit>, [">= 0"])
    else
      s.add_dependency(%q<net-scp>, [">= 0"])
      s.add_dependency(%q<highline>, [">= 0"])
      s.add_dependency(%q<copier>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<mocha>, [">= 0"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<test-unit>, [">= 0"])
    end
  else
    s.add_dependency(%q<net-scp>, [">= 0"])
    s.add_dependency(%q<highline>, [">= 0"])
    s.add_dependency(%q<copier>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<mocha>, [">= 0"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<test-unit>, [">= 0"])
  end
end

