# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{keyrack}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jeremy Stephens"]
  s.date = %q{2010-12-12}
  s.default_executable = %q{keyrack}
  s.description = %q{Simple password manager with local/remote database storage and RSA encryption.}
  s.email = %q{viking@pillageandplunder.net}
  s.executables = ["keyrack"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/keyrack",
    "lib/keyrack.rb",
    "lib/keyrack/database.rb",
    "lib/keyrack/runner.rb",
    "lib/keyrack/store.rb",
    "lib/keyrack/store/filesystem.rb",
    "lib/keyrack/store/ssh.rb",
    "lib/keyrack/ui.rb",
    "lib/keyrack/ui/console.rb",
    "test/fixtures/config.yml",
    "test/fixtures/foo.txt",
    "test/fixtures/id_rsa",
    "test/fixtures/id_rsa.pub",
    "test/helper.rb",
    "test/keyrack/store/test_filesystem.rb",
    "test/keyrack/store/test_ssh.rb",
    "test/keyrack/test_database.rb",
    "test/keyrack/test_runner.rb",
    "test/keyrack/test_store.rb",
    "test/keyrack/ui/test_console.rb"
  ]
  s.homepage = %q{http://github.com/viking/keyrack}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Simple password manager}
  s.test_files = [
    "test/helper.rb",
    "test/keyrack/store/test_filesystem.rb",
    "test/keyrack/store/test_ssh.rb",
    "test/keyrack/test_database.rb",
    "test/keyrack/test_runner.rb",
    "test/keyrack/test_store.rb",
    "test/keyrack/ui/test_console.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<net-scp>, [">= 0"])
      s.add_runtime_dependency(%q<highline>, [">= 0"])
      s.add_runtime_dependency(%q<clipboard>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<mocha>, [">= 0"])
    else
      s.add_dependency(%q<net-scp>, [">= 0"])
      s.add_dependency(%q<highline>, [">= 0"])
      s.add_dependency(%q<clipboard>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<mocha>, [">= 0"])
    end
  else
    s.add_dependency(%q<net-scp>, [">= 0"])
    s.add_dependency(%q<highline>, [">= 0"])
    s.add_dependency(%q<clipboard>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<mocha>, [">= 0"])
  end
end

